
import * as yarnParsers from '@yarnpkg/parsers';

export type YarnEntry = {
  version: string
  resolution: string
  dependencies?: Record<string, string>
  checksum?: string;
  languageName?: 'node'
  linkType?: 'hard' | 'soft'
}

export type YarnEntries = Record<string, YarnEntry>;


export const parseYarnLock = (file:string) => yarnParsers.parseSyml(file) as YarnEntries;


const yarnLockHeader = `${[
  `# This file is generated by running "yarn install" inside your project.\n`,
  `# Manual changes might be lost - proceed with caution!\n`,
].join(``)}\n`;


export const stringifyYarnLock = (yarnEntries: YarnEntries) => yarnLockHeader + yarnParsers.stringifySyml(yarnEntries);